### ISSUE TITLE
publishing message error, not support Chinese tag, capital tag, picture in contents

### ISSUE THREAD

**Issue by meichiny** [vasanth9/hash-dian#3]
I installed the plugin and setup API. When publishing to hashnode by `basic publishing`, it tells me some error message, maybe not support Chinese tags, capital tags, picture in contents.

**Comment by vasanth9** [comment]
Hi @chinsansan  Hashnode api is expecting the [a-z0-9-]{1,250} type for tags, as Chinese  words  and capital letters fail this regex validation. Error is coming. Try giving the tags that satisfy the regex. and for pictures also not allowed as of now with the hashnode api.

**Comment by meichiny** [comment]
> Hi @chinsansan Hashnode api is expecting the [a-z0-9-]{1,250} type for tags, as Chinese words and capital letters fail this regex validation. Error is coming. Try giving the tags that satisfy the regex. and for pictures also not allowed as of now with the hashnode api.

OK, I got it. Thanks.
